apiVersion: v1
kind: Namespace
metadata:
  name: twistlock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: twistlock-service-account
  namespace: twistlock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twistlock-clusterrole
rules:
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources: 
  - "clusterroles"
  - "clusterrolebindings"
  verbs: 
  - "create"
  - "delete"
  - "list"
- apiGroups: 
  - ""
  resources:
  - "namespaces"
  verbs: 
  - "create"
  - "get"
- apiGroups:
  - "apps"
  - "rbac.authorization.k8s.io"
  resources: 
  - "daemonsets"
  - "roles"
  - "rolebindings"
  verbs:
  - "list"
- apiGroups:
  - ""
  - "apps"
  resources:
  - "deployments"
  - "replicasets"
  - "pods"
  verbs:
  - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: twistlock-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: twistlock-service-account
  namespace: twistlock
roleRef:
  kind: ClusterRole
  name: twistlock-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: twistlock-role
  namespace: twistlock
rules: 
- apiGroups: 
  - ""
  - "apps"
  - "rbac.authorization.k8s.io"
  resources: 
  - "daemonsets"
  - "secrets"
  - "serviceaccounts"
  - "services"
  verbs: 
  - "create"
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: twistlock-rolebinding
  namespace: twistlock
subjects:
- kind: ServiceAccount
  name: twistlock-service-account
  namespace: twistlock
roleRef:
  kind: Role
  name: twistlock-role
  apiGroup: rbac.authorization.k8s.io
